#include "constants.h"

const char* PasswordsSubContainerStylesheet =
    "#passwordsSubcontainer{"
    "    background-color: rgb(57, 73, 94); "
    "    border-radius: 26px;"
    "}"
    ""
    "#passwordsSubcontainer QLabel{"
    "    color: rgb(153, 234, 255);"
    "    font: 10pt \"Segoe UI\";"
    "    /*qproperty-alignment: AlignCenter;*/"
    "}"
    ""
    "#passwordsSubcontainer QPushButton{"
    "    border-radius: 12px;"
    "    background-color: rgb(57, 73, 94);"
    "}"
    ""
    "#passwordsSubcontainer QPushButton:hover {"
    "    background-color: rgb(55, 113, 167);"
    "}"
    ""
    "#passwordsSubcontainer QPushButton:pressed{"
    "    background-color: #34699D;"
    "}"
    ""
    "#passwordsSubcontainer QLineEdit{"
    "    color: rgb(153, 234, 255);"
    "    /*qproperty-alignment: AlignCenter;*/"
    "}";

const char* AdvancedFrameButtonDisabledStylesheet =
    "QPushButton{"
    "color: rgb(220, 220, 220);"
    "font: 9pt \"Segoe UI\";"
    "background-color: rgb(57, 73, 94);"
    "}"
    ""
    "QPushButton:hover{"
    "background-color: rgb(65, 83, 107);"
    "}"
    ""
    "QPushButton:pressed{"
    "background-color: rgb(51, 65, 84);"
    "}";
